name: Normalize Composer.json

on: [pull_request]

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }} # Ensure the branch is checked out instead of a detached HEAD

      - name: Normalize Composer.json
        run: |
          composer global config --no-plugins allow-plugins.ergebnis/composer-normalize true
          composer global require ergebnis/composer-normalize
          composer normalize

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Normalize Composer.json
