name: Normalize Composer.json

on: [pull_request]

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main  # Replace 'main' with the target branch you want to commit to

      - name: Normalize Composer.json
        run: |
          composer global config --no-plugins allow-plugins.ergebnis/composer-normalize true
          composer global require ergebnis/composer-normalize
          composer normalize

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Normalize Composer.json
